pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                               // Will get the code from this git repo location to build images
                            //Now our jenkins node will point to this repo.
                git credentialsId: '23232-efw3e-e312-df2dd-12312-dsd87', 
                url: 'https://github.com/charanraj-1/Jenkins-Zero-To-Hero/python-jenkins-argocd-k8s',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    //Build docker image with docker hub directory and specific name tag.
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t charanraj1/mybuild-images:todoapp${BUILD_NUMBER} .
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push charanraj1/mybuild-images:todoapp${BUILD_NUMBER}
                    '''
                }
            }
        }
        
        stage('Checkout K8S manifest SCM'){
                     // Now checking out this repo of git for accessing code or to update the files.
                    // we are giving access to Jenkins node this repo
            steps {
                git credentialsId: '23232-efw3e-e312-df2dd-12312-dsd87', 
                url: 'https://github.com/charanraj-1/cicd-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest & push to Repo'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: '23232-efw3e-e312-df2dd-12312-dsd87', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i '' "s/0/${BUILD_NUMBER}/g" deploy.yaml
                        cat deploy.yaml
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        git push https://github.com/charanraj-1/cicd-manifests-repo.git HEAD:main
                        '''        
                        //sed -i "s/0/${BUILD_NUMBER}/g" deploy.yaml
                        // streamEditor -i -> edit, s -> substitute, 0 with ${build_number}, g -> globally. 
                    }
                }
            }
        }
    }
}
